version: "3.8"

services:
  
  backend:
    build:
      context: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env 
    volumes:
      - ./backend:/app
    environment:
      - ENV=production  

  frontend:
    build:
      context: ./frontend
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    mem_limit: 4g # increasing javascript memory limit cause it hates me 
    mem_reservation: 2g  # Soft memory limit (2 GB)



