services:
  
  backend:
    build:
      context: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env 
    volumes:
      - ./backend:/app
    environment:
      - ENV=production 
    networks:
      - app-network 

  frontend:
    build:
      context: ./frontend
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./.env  # Changed to use root .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:8000
    networks:
      - app-network
    depends_on:
      - backend
    mem_limit: 4g # increasing javascript memory limit cause it hates me 
    mem_reservation: 2g  # Soft memory limit (2 GB)

networks:
  app-network:
    driver: bridge



